services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: trello
      POSTGRES_PASSWORD: trello
      POSTGRES_DB: trello
    ports:
      - 0.0.0.0:5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
